[package]
name = "lua-runtime-test"
version = "0.1.0"
edition = "2024"

[features]
luajit = ["mlua/luajit52", "mlua/vendored"]
luau = ["mlua/luau-jit"]
lua54 = ["mlua/lua54", "mlua/vendored"]

[dependencies]
mlua = { version = "0.11.4", optional = true }
peak_alloc = "0.3.0"
